config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
	resources :blog_posts
	resources :comments, only: [:edit, :create, :update, :destroy]
	root 'blog_posts#index'

	get 'your_posts' => 'blog_posts#your_posts'

	get 'user_profile' => 'blog_posts#user_profile'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

	has_many :comments
	belongs_to :user

	validates :title, :blog_entry, presence: true
	validates :title, uniqueness: true, length: {maximum: 140}
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :blog_post
	belongs_to :user

	validates :comment_entry, :blog_post_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :blog_posts
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :birthday])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :birthday])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  def index
  	@blog_posts = BlogPost.all
  end

  def show
  	@comment = Comment.new
  end

  def user_profile
  	@user = User.find(params[:id])
  end

  def your_posts
  end

  def edit
  end

  def new
  	@blog_post = BlogPost.new
  end

  def create
  	@blog_post = BlogPost.new(blog_post_params)

  	respond_to do |format|
  		if @blog_post.save
  			format.html {redirect_to @blog_post, notice: "Blog post created successfully."}
  		else
  			format.html {render :edit}
  		end
  	end
  end

	def update

		respond_to do |format|
			if @blog_post.update(blog_post_params)
			format.html{redirect_to @blog_post, notice: "Blog post was updated successfully."}
			else
			format.html{render :edit}
			end
		end
	end

	def destroy
		@blog_post.destroy

		respond_to do |format|
			format.html {redirect_to blog_posts_url, notice: "Your blog post was destroyed."}
		end
	end

	private

	def blog_post_params
	params.require(:blog_post).permit(:title, :blog_entry, :user_id)
	end

	def set_blog_post
	@blog_post = BlogPost.find(params[:id])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_comment, only: [:edit, :update, :destroy]

  def edit
  end

  def create
  	@comment = Comment.new(comment_params)

  	respond_to do |format|
  		if @comment.save
  			format.html{redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment was successfully created.'}
  		else
  			format.html{redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment failed to post.'}
  		end
  	end
  end


def update
	respond_to do |format|
		if @comment.update(comment_params)
			format.html{redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment was successfully updated.'}
		else
			format.html{render :edit}
		end
	end
  end

def destroy
	@comment.destroy
	respond_to do |format|
		format.html{redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment was destroyed.'}
	end
  end



private

  def comment_params
  	params.require(:comment).permit(:user_id, :comment_entry, :blog_post_id)
  end

  def set_comment
  	@comment = Comment.find(params[:id])
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
	<% if @blog_post.errors.any? %>
	<div class="error_explanation">
		<h1><%= pluralize(@blog_post.errors.count, "error") %>
		prohibited this blog post from being saved:</h1>

		<ul>
			<% @blog_post.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="form-group">
		<%= f.text_field :title, class: "form-control", placeholder: "Enter your cool blog post name here.." %>
	</div>

	<div class="form-group hidden">
		<%= f.text_field :user_id, value: current_user.id %>
	</div>

	<div class="form-group">
		<%= f.text_area :blog_entry, class: "form-control", rows: '12', placeholder: "start typing" %>
	</div>

	<div class="actions">
		<%= f.submit 'Post', class: "btn btn-default" %>
	</div>
<% end %>

app/views/blog_posts/edit.html.erb
<div class="container">

<h1>Editing Blog Post</h1>



<%= render "form" %>



<br>

<div>
  <%= link_to "Back", @blog_post, class: "btn btn-info" %>
  <%= link_to "All Blog Posts", blog_posts_path, class:"btn btn-primary" %>
  </div>
</div>

app/views/blog_posts/index.html.erb
<div class="container">

<h1>Blog Posts</h1>

  <h1>Welcome <%= current_user.username %></h1>

<div class="row">
	<% @blog_posts.each do |blog_post| %>
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<%= link_to blog_post.title, blog_post %>
			</div>
			<div class="panel-body">
				by <%= link_to blog_post.user.username, user_profile_path(id: blog_post.user.id) %> <br>
				<p>Created at: <%= blog_post.created_at.strftime('%m/%d/%Y at %I:%M%p') %></p>
				<p><%= blog_post.blog_entry[0..500] %>...<%= link_to "Read more", blog_post%></p>
			</div>
			<div class="panel-footer">
			  <% if current_user.id == blog_post.user.id %>
				<%= link_to 'Show', blog_post, class: "btn btn primary" %>
				<%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
				<%= link_to 'Destroy', blog_post, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
			</div>
			<%end%>
		</div>
	</div>
	<% end %>
</div>

<br>

<div>
<%= link_to 'New Blog Post', new_blog_post_path %>
</div>

</div>

app/views/blog_posts/new.html.erb
<div class="container">

<h1>Create a new Blog Post</h1>

	<%= render "form" %>

<div>
<%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-primary" %>
</div>
</div>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<dic class="container">

<div class="panel panel-primary">
	<div class="panel-heading">
		<%= @blog_post.title %>
	</div>

	<div class="panel-body">
		<p><%= link_to @blog_post.user.username, user_profile_path(id: @blog_post.user.id) %></p>
		<p><%= time_ago_in_words(@blog_post.created_at) %></p>
		<p><%= @blog_post.blog_entry %></p>
	</div>
</div>
	<div class="panel-footer">
	<% if current_user.id == @blog_post.user.id %>
	<div>
		<%= link_to 'Edit', edit_blog_post_path(@blog_post), class: "btn btn-warning" %>
		<%= link_to 'All Blog Post', blog_posts_path, class: "btn btn-primary" %>
	</div>
	<% end %>
	</div>

<div class="panel panel-default">
	<div class="panel-heading">
		Comments
	</div>
	<div class="panel-body">
		<%= render @comment %>
	</div>
</div>

<div class="panel panel-success">
	<div class="panel-heading">
		Make a comment
	</div>
	<div class="panel-body">
		<%= render 'comments/form' %>
	</div>
</div>



<div>
	<%= link_to 'All Blog Posts', blog_posts_path, class: 'btn btn-primary' %>
</div>

app/views/blog_posts/user_profile.html.erb
<div class="container">

  <h1><%= @user.username %> 's Page</h1>

  <p><strong>Name:</strong><%= @user.name %></p>

  <p><strong>Birthday:</strong><%= @user.birthday.strftime("%m/%d/%Y") %></p>

  <div class="row">
    <% @user.blog_posts.each do |blog_post| %>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to blog_post.title, blog_post %>
          </div>
          <div class="panel-body">
            by <%= blog_post.user.username %><br>
            <p>Create at: <%= blog_post.created_at strftime('%m/%d/%Y at %I:%M%p') %></p>
            <p><%= blog_post.blog_entry[0..500] %>...<%= link_to "Read More", blog_post %></p>
            </div>
            <div class="panel-footer">
              <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
              <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    <div>
      <%= link_to 'New Blog Post', new_blog_post_path,
      class: "btn btn-primary" %>
  </div>
</div>

app/views/blog_posts/your_posts.html.erb
<div class="container">

  <h1>Your Posts</h1>

  <div class="row">
    <% current_user.blog_posts.each do |blog_post| %>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to blog_post.title, blog_post %>
          </div>
          <div class="panel-body">
            by <%= blog_post.user.username %><br>
            <p>Create at: <%= blog_post.created_at strftime('%m/%d/%Y at %I:%M%p') %></p>
            <p><%= blog_post.blog_entry[0..500] %>...<%= link_to "Read More", blog_post %></p>
            </div>
            <div class="panel-footer">
              <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
              <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    <div>
      <%= link_to 'New Blog Post', new_blog_post_path,
      class: "btn btn-primary" %>
  </div>
</div>

app/views/comments/_comment.html.erb
<% @blog_post.comments.each do |comment| %>
	<h4><%= link_to comment.user.username, user_profile_path(id: comment.user.id) %></h4>
	<p><%= time_ago_in_words(comment.created_at) %></p>
	<p><%= comment.comment_entry %></p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
    <% if @comment.errors.any? %>
    <div class="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this blog post from being saved:</h2>
        <ul>
            <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
<div class="form-group hidden">
        <%= f.text_field :user_id, value: current_user.id %>
</div>
<div class="form-group">
    <%= f.text_area :comment_entry, class: "form-control", rows: '3', placeholder: "Enter comment here" %>
</div>
<div class="form-group hidden">
    <%= f.number_field :blog_post_id, value: @blog_post.id %>
</div>
<div class="actions">
    <%= f.submit "Comment", class: "btn btn-default" %>
</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>

<nav class="navbar navbar-default">
<div class="container-fluid">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed"
    data-toggle="collapse"
    data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>


    <ul class="nav navbar-nav navbar-left">

      <li><%= link_to "All Posts", your_posts_path %></li>
      <li><%= link_to "New Blog Posts", new_blog_post_path %></li>
    </ul>
  </div>

  <div class="collapse-navbar-collapse" id="bs-example-navbar-collapse-1">

  	<ul class="nav navbar-nav navbar-right">
  	  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
  	  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
  	</ul>

  	</div>
  </div>
 </nav>

 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TtsBlog</title>

    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>
    
    <%= yield %>

    <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>